### ISSUE TITLE
Gnome 42 support

### ISSUE THREAD

**Issue by stdevPavelmc** [Harshan01/Cloudflare-WARP-GNOME-Switcher#1]
Fedora and Ubuntu has imminent stable releases with Gnome 42, and  this extension is not supported.

So please add support for Gnome 42

**Comment by Harshan01** [comment]
Thanks for raising this issue. Bumped supported versions to 41 and 42 in commit db5569e6f40b2a24614aa5d78ee2a0da9ef67625

Closing this issue. Feel free to reopen in case of any problem
