### ISSUE TITLE
Call `_getWARPStatus` and update at regular intervals

### ISSUE THREAD

**Issue by Syzygianinfern0** [Harshan01/Cloudflare-WARP-GNOME-Switcher#3]
Not sure if this would be along the design choices of the extension, but it would be helpful to refresh the status of the icon regularly. This is essential so that it reflects the actual status of the WARP (maybe the user either activated through the terminal, as a startup script, or as an Exec hook rather than through the extension).

**Comment by Harshan01** [comment]
I agree, this is a required change as the extension icon goes out of sync when toggling multiple times quickly. Keeping this issue open till fixed

**Comment by Harshan01** [comment]
Automatic status updates are added in commit 8ac0d838d17bdf5367391a4f727fa2941db1a06f. Extension Prefs are added. You can change the frequency of update in the Prefs. Closing issue.
